version: "2"
services:
  web:
    hostname: "dkan"
    environment:
      - VIRTUAL_HOST=dkan
      - no_proxy=localhost
      #- VIRTUAL_PROTO=https
  cli:
    environment:
      - PHP_IDE_CONFIG=serverName=dkan
      - VIRTUAL_HOST=dkan
